-- Phase 1: ADT1 pilot table
CREATE TABLE IF NOT EXISTS adt1_submissions (
    id SERIAL PRIMARY KEY,
    ref_user_id INTEGER,
    company_id INTEGER NOT NULL,
    cin VARCHAR(50) NOT NULL,
    company_name VARCHAR(255) NOT NULL,
    company_address VARCHAR(500),
    company_email VARCHAR(255),
    falling_section VARCHAR(255),
    appointment_nature VARCHAR(255),
    is_auditor_appointed VARCHAR(50),
    auditor_number NUMERIC,
    annual_general_meeting VARCHAR(255),
    agm_date TIMESTAMP,
    appointment_date TIMESTAMP,
    is_casual_vacancy VARCHAR(50),
    srn_of_relevant_form VARCHAR(255),
    person_vacated VARCHAR(255),
    vacancy_date TIMESTAMP,
    casual_vacancy_reasons VARCHAR(500),
    membership_number NUMERIC,
    auditor_serial BOOLEAN,
    auditor_member_no VARCHAR(255),
    resolution_number VARCHAR(255),
    resolution_date TIMESTAMP,
    signed_by VARCHAR(255),
    designation VARCHAR(255),
    din VARCHAR(50),
    ref_user_name VARCHAR(255),
    created_at TIMESTAMP DEFAULT NOW()
);
