-- Phase 2: BEN2 table
CREATE TABLE IF NOT EXISTS ben2_submissions (
    id SERIAL PRIMARY KEY,
    ref_user Integer NULL,
    company_id Integer NULL,
    cin VARCHAR(255) NULL,
    company_name VARCHAR(255) NULL,
    company_address VARCHAR(255) NULL,
    company_email VARCHAR(255) NULL,
    reporting_company Boolean NULL,
    declaration_ownership Boolean NULL,
    change_ownership Boolean NULL,
    change_exiting Boolean NULL,
    change_reporting_company Boolean NULL,
    cin_holding_company Integer NULL,
    name_holding_company VARCHAR(255) NULL,
    number_of_significant_owners Integer NULL,
    copy_attachment VARCHAR(255) NULL,
    optional_attachment VARCHAR(255) NULL,
    resolution_number Integer NULL,
    resolution_date TIMESTAMP NULL,
    designation VARCHAR(255) NULL,
    signitory VARCHAR(255) NULL,
    din_pan VARCHAR(255) NULL,
    category VARCHAR(255) NULL,
    name_of_pcs VARCHAR(255) NULL,
    associate_or_fellow VARCHAR(255) NULL,
    membership_number Integer NULL,
    ref_user_name VARCHAR(255) NULL,
    created_at TIMESTAMP DEFAULT NOW()
);