-- Phase 2: PAS3 table
CREATE TABLE IF NOT EXISTS pas3_submissions (
    id SERIAL PRIMARY KEY,
    ref_user Integer NULL,
    company_id Integer NULL,
    cin VARCHAR(255) NULL,
    company_name VARCHAR(255) NULL,
    company_address VARCHAR(255) NULL,
    company_email VARCHAR(255) NULL,
    number_of_allotments Integer NULL,
    no_of_classes_preference Integer NULL,
    no_of_classes_equity Integer NULL,
    no_of_unclassified Integer NULL,
    total_unclassified Integer NULL,
    debentures Integer NULL,
    loan_secured Integer NULL,
    others Integer NULL,
    equity_authorized_capital VARCHAR(255) NULL,
    equity_paidup_capital VARCHAR(255) NULL,
    allottees_list VARCHAR(255) NULL,
    another_attachment VARCHAR(255) NULL,
    optional_attachment VARCHAR(255) NULL,
    resolution_number VARCHAR(255) NULL,
    resolution_date TIMESTAMP NULL,
    designation VARCHAR(255) NULL,
    signatory VARCHAR(255) NULL,
    category VARCHAR(255) NULL,
    name_of_pcs VARCHAR(255) NULL,
    assososiate_or_fellow VARCHAR(255) NULL,
    membership_number Integer NULL,
    equity_share_list VARCHAR(255) NULL,
    preference_share_list VARCHAR(255) NULL,
    ref_user_name VARCHAR(255) NULL,
    parent_id Integer NULL,
    type VARCHAR(255) NULL,
    class_of_shares VARCHAR(255) NULL,
    authorized_capital Float NULL,
    issued_capital Float NULL,
    subscribed_capital Float NULL,
    paid_up_capital Float NULL,
    nominal_amount_per_share Float NULL,
    nominal_amount_per_share_issue Float NULL,
    nominal_amount_per_share_sub Float NULL,
    nominal_amount_per_share_paid Float NULL,
    total_amount_shares Float NULL,
    total_amount_shares_issue Float NULL,
    total_amount_shares_sub Float NULL,
    total_amount_shares_paid Float NULL,
    deleted_on TIMESTAMP NULL,
    created_at TIMESTAMP DEFAULT NOW()
);